// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwRuEPptS-I6KFsTEUAn8l4ITbOhhxbE',
    appId: '1:1062871212993:web:9441eb4438b9326b788540',
    messagingSenderId: '1062871212993',
    projectId: 'lost-found-campus-9daa8',
    authDomain: 'lost-found-campus-9daa8.firebaseapp.com',
    databaseURL: 'https://lost-found-campus-9daa8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lost-found-campus-9daa8.firebasestorage.app',
    measurementId: 'G-2ED68K9K2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk5NBxxcmseft8oEm-H8DaPPYNpkUWZnw',
    appId: '1:1062871212993:android:ccf37594d81e9f25788540',
    messagingSenderId: '1062871212993',
    projectId: 'lost-found-campus-9daa8',
    databaseURL: 'https://lost-found-campus-9daa8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lost-found-campus-9daa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeAadEaKIX87yJ2TijgQp4edGgcNNddU',
    appId: '1:1062871212993:ios:9890d3e345034a16788540',
    messagingSenderId: '1062871212993',
    projectId: 'lost-found-campus-9daa8',
    databaseURL: 'https://lost-found-campus-9daa8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lost-found-campus-9daa8.firebasestorage.app',
    androidClientId: '1062871212993-u812h0f8bv02bsf7oc9nv85f1l3dplbb.apps.googleusercontent.com',
    iosClientId: '1062871212993-8hpdhdj5bargmraee7h2l9up9vermscm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostFoundCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeAadEaKIX87yJ2TijgQp4edGgcNNddU',
    appId: '1:1062871212993:ios:9890d3e345034a16788540',
    messagingSenderId: '1062871212993',
    projectId: 'lost-found-campus-9daa8',
    databaseURL: 'https://lost-found-campus-9daa8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lost-found-campus-9daa8.firebasestorage.app',
    androidClientId: '1062871212993-u812h0f8bv02bsf7oc9nv85f1l3dplbb.apps.googleusercontent.com',
    iosClientId: '1062871212993-8hpdhdj5bargmraee7h2l9up9vermscm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostFoundCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIwRuEPptS-I6KFsTEUAn8l4ITbOhhxbE',
    appId: '1:1062871212993:web:100fbc6340087dee788540',
    messagingSenderId: '1062871212993',
    projectId: 'lost-found-campus-9daa8',
    authDomain: 'lost-found-campus-9daa8.firebaseapp.com',
    databaseURL: 'https://lost-found-campus-9daa8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lost-found-campus-9daa8.firebasestorage.app',
    measurementId: 'G-Q6C63ZLQ16',
  );

}